server:
  port: 8888
spring:
  application:
    name:config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AlbertoGomez1979/Bootcamp-micro.git
        default-label: main
        search-paths:
        - '*service*'
